### ISSUE TITLE
Standardize plugin errors

### ISSUE THREAD

**Issue by lare96** [lare96/luna#49]
Errors thrown by plugins are objectively a complete and total eyesore. They're unnecessarily bloated, and can look vastly different from one another depending on when the error is thrown (evaluation or application). Take for example, the following two different types of errors

Application error
```
21 Jul 2017 18:45:07 io.luna.game.event.EventListener [LunaGameThread RUNNING]
ERROR: Catching
io.luna.game.plugin.PluginFailureException: 2570 (of class java.lang.Integer)
	at io.luna.game.event.EventListener.apply(EventListener.java:57) ~[classes/:?]
	at io.luna.game.event.EventListenerPipeline.traverse(EventListenerPipeline.java:59) ~[classes/:?]
	at io.luna.game.plugin.PluginManager.post(PluginManager.java:43) ~[classes/:?]
	at io.luna.game.model.item.Equipment$EquipmentListener.sendEvent(Equipment.java:77) ~[classes/:?]
	at io.luna.game.model.item.Equipment$EquipmentListener.onBulkUpdate(Equipment.java:62) ~[classes/:?]
	at io.luna.game.model.item.ItemContainer.fireUpdateEvent(ItemContainer.java:832) ~[classes/:?]
	at io.luna.game.model.item.ItemContainer.set(ItemContainer.java:717) ~[classes/:?]
	at io.luna.game.model.item.Equipment.add(Equipment.java:263) ~[classes/:?]
	at io.luna.game.model.item.ItemContainer.addAll(ItemContainer.java:248) ~[classes/:?]
	at $line40.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$new$1(<console>:205) ~[?:?]
	at $line40.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$new$1$adapted(<console>:199) ~[?:?]
	at $line5.$read$$iw$$iw$$anon$1.accept(<console>:185) ~[?:?]
	at io.luna.game.event.EventListener.apply(EventListener.java:49) ~[classes/:?]
	at io.luna.game.event.EventListenerPipeline.traverse(EventListenerPipeline.java:59) ~[classes/:?]
	at io.luna.game.plugin.PluginManager.post(PluginManager.java:43) ~[classes/:?]
	at io.luna.game.model.mobile.Player.onActive(Player.java:279) ~[classes/:?]
	at io.luna.game.model.Entity.setState(Entity.java:139) ~[classes/:?]
	at io.luna.game.model.mobile.MobList.add(MobList.java:195) ~[classes/:?]
	at io.luna.game.model.World.dequeueLogins(World.java:96) ~[classes/:?]
	at io.luna.game.GameService.runOneIteration(GameService.java:78) ~[classes/:?]
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:188) ~[guava-22.0.jar:?]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) ~[guava-22.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: scala.MatchError: 2570 (of class java.lang.Integer)
	at $line47.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$new$2(<console>:211) ~[?:?]
	at scala.runtime.java8.JFunction1$mcZI$sp.apply(JFunction1$mcZI$sp.java:12) ~[scala-library-2.12.2.jar:?]
	at scala.Option.foreach(Option.scala:257) ~[scala-library-2.12.2.jar:?]
	at $line47.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$new$1(<console>:209) ~[?:?]
	at $line47.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$new$1$adapted(<console>:206) ~[?:?]
	at $line5.$read$$iw$$iw$$anon$1.accept(<console>:185) ~[?:?]
	at io.luna.game.event.EventListener.apply(EventListener.java:49) ~[classes/:?]
	... 28 more
```

Evaluation error
```
21 Jul 2017 20:33:50 io.luna.game.plugin.PluginBootstrap [LunaInitializationThread]
ERROR: Catching
javax.script.ScriptException: unbound placeholder parameter in import io.luna.game.event.Event
import io.luna.game.event.impl.{ButtonClickEvent, EquipmentChangeEvent}
import io.luna.game.model.item.Equipment.RING
import io.luna.game.model.mobile.Player


private val RING_OF_STONE = 6583
private val STONE_MORPH = 2626

private val EASTER_RING = 7927
private val EGGS_MORPH = Vector(3689, 3690, 3691, 3692, 3693, 3694)


private def morph(plr: Player, msg: Event, to: Int) = {
  (0 to 13).filterNot(_ == 3).foreach(plr.sendTabInterface(_, -1))
  plr.sendForceTab(3)
  plr.sendTabInterface(3, 6014)

  plr.lockMovement
  plr.transform(to)
  msg.terminate
}

private def unmorph(plr: Player) = {
  if (plr.inventory.computeRemainingSize > 1) {
    plr.equipment.unequip(RING)

    plr.displayTabInterfaces()

    plr.unlockMovement
    plr.transform(-1)
  } else {
    plr.sendMessage("You do not have enough space in your inventory.")
  }
}


on[EquipmentChangeEvent] { msg =>
  if (msg.index == RING) {

    msg.newId.foreach {
      case RING_OF_STONE => morph(msg.plr, msg, STONE_MORPH)
      case EASTER_RING => morph(msg.plr, msg, rand(EGGS_MORPH))
      case _ => _
    }
  }
}

// unmorph (figure out proper id)
onargs[ButtonClickEvent](23132) { msg => unmorph(msg.plr) } at line number 44 at column number 17
	at scala.tools.nsc.interpreter.Scripted.$anonfun$compile$2(Scripted.scala:163) ~[scala-compiler-2.12.2.jar:?]
	at scala.tools.nsc.interpreter.Scripted.$anonfun$compile$1(Scripted.scala:162) ~[scala-compiler-2.12.2.jar:?]
	at scala.tools.nsc.interpreter.Scripted.withCompileContext(Scripted.scala:134) ~[scala-compiler-2.12.2.jar:?]
	at scala.tools.nsc.interpreter.Scripted.compile(Scripted.scala:148) ~[scala-compiler-2.12.2.jar:?]
	at scala.tools.nsc.interpreter.Scripted.eval(Scripted.scala:181) ~[scala-compiler-2.12.2.jar:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[?:1.8.0_131]
	at io.luna.game.plugin.PluginBootstrap.initPlugins(PluginBootstrap.java:220) ~[classes/:?]
	at io.luna.game.plugin.PluginBootstrap.init(PluginBootstrap.java:170) ~[classes/:?]
	at io.luna.game.plugin.PluginBootstrap.call(PluginBootstrap.java:132) ~[classes/:?]
	at io.luna.game.plugin.PluginBootstrap.call(PluginBootstrap.java:40) ~[classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[guava-22.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[guava-22.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[guava-22.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

In order to begin the standardization of plugin errors, a few prerequisites must be met

- Remove ScalaConsole from PluginBootstrap (No longer needed in Scala 2.12)
- Scrap PluginFailureException and ScriptException
- EventListeners store the plugin file name as metadata

And the new standard *should* look something like
```
ERROR: FAILED: 'my_plugin.scala' 
  CAUSED BY: unbound placeholder parameter
  @ LINE 50: case _ => _
```

**Comment by lare96** [comment]
Evaluation errors have been fixed. Instead of displaying the whole file and giving inaccurate line/coloumn numbers, it now looks like.

```
io.luna.game.plugin.ScriptLoadException: 
		INTERPRET FAILED: fields.scala
		REASON: ';' expected but identifier found.
		@ LINES: 
	> import io.luna.game.model.mob.{PlayerRights, Skill}
	> import io.luna.util.Rational
	> import org.apache.logging.log4j.Logger FAIL HERE PLEASE!!!
	> 
	> 
	> /* The injected state. */
	> val ctx = $context$.asInstanceOf[LunaContext]

	at io.luna.game.plugin.PluginBootstrap.loadPlugin(PluginBootstrap.java:286) ~[classes/:?]
	at io.luna.game.plugin.PluginBootstrap.initPlugins(PluginBootstrap.java:261) ~[classes/:?]
	at io.luna.game.plugin.PluginBootstrap.init(PluginBootstrap.java:197) ~[classes/:?]
	at io.luna.LunaServer.initPlugins(LunaServer.java:124) ~[classes/:?]
	at io.luna.LunaServer.init(LunaServer.java:79) ~[classes/:?]
	at io.luna.Luna.main(Luna.java:47) ~[classes/:?]
```

Application errors still simply forward the underlying cause exception to the superclass. AFAIK there isn't really an ideal workaround for this. I don't think it'll be too much of an issue, since the vast majority of errors are evaluation and not application.
