### ISSUE TITLE
Is this project in a working state?

### ISSUE THREAD

**Issue by gravypod** [lare96/luna#55]
Hey. I was just trying to start a runescape server for a friend and I to play offline. I was unable to get your code to start. I compiled and when I ran the jar I got this:

```
Exception in thread "LunaInitializationThread" java.lang.NoClassDefFoundError: com/moandjiezana/toml/Toml
	at io.luna.LunaConstants.<clinit>(LunaConstants.java:25)
	at io.luna.Luna.<clinit>(Luna.java:29)
Caused by: java.lang.ClassNotFoundException: com.moandjiezana.toml.Toml
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

Is the code in a state where it can be run? Thanks.

**Comment by lare96** [comment]
Yes, the CI build is passing and the server can be ran. Your error refers to a missing dependency, are you using Maven?

**Comment by InfinitySamurai** [comment]
It seems that this problem may be a result of a lack of documentation on how to set up the project. Could the README be augmented to include what needs to be done to get it started?

**Comment by lare96** [comment]
I was planning to do that once the project hits 1.0.0 but I could start working on it now.

**Comment by eatbeans2** [comment]
How do you compile this with maven? I can't seem to get it to run after compiling, but I'm probably using Maven wrong.

**Comment by lare96** [comment]
Are you using an IDE? If so which one?

**Comment by eatbeans2** [comment]
No IDE. Compiling in terminal on OSX and it can't find main...
