### ISSUE TITLE
Client Disconnects and Crashes Server

### ISSUE THREAD

**Issue by AshotN** [lare96/luna#75]
Downloaded the Asteria 2.0 Client, and every-time I login, it loads and a few seconds past it disconnects
and crashes the server. 

If you could tell me how to resolve the client issue, and there should also be a check for invalid byte size to avoid a crash.

```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -javaagent:/snap/intellij-idea-ultimate/79/lib/idea_rt.jar=46033:/snap/intellij-idea-ultimate/79/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/home/hego555/IdeaProjects/luna/target/classes:/home/hego555/.m2/repository/com/google/code/gson/gson/2.8.1/gson-2.8.1.jar:/home/hego555/.m2/repository/org/apache/logging/log4j/log4j-core/2.8.2/log4j-core-2.8.2.jar:/home/hego555/.m2/repository/org/apache/logging/log4j/log4j-api/2.8.2/log4j-api-2.8.2.jar:/home/hego555/.m2/repository/com/lmax/disruptor/3.3.6/disruptor-3.3.6.jar:/home/hego555/.m2/repository/io/netty/netty-all/4.1.27.Final/netty-all-4.1.27.Final.jar:/home/hego555/.m2/repository/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar:/home/hego555/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/hego555/.m2/repository/org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar:/home/hego555/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/home/hego555/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/home/hego555/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/home/hego555/.m2/repository/com/moandjiezana/toml/toml4j/0.7.1/toml4j-0.7.1.jar:/home/hego555/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/hego555/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/hego555/.m2/repository/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar:/home/hego555/.m2/repository/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar:/home/hego555/.m2/repository/org/scala-lang/scala-compiler/2.12.6/scala-compiler-2.12.6.jar:/home/hego555/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar:/home/hego555/.m2/repository/org/functionaljava/functionaljava/4.7/functionaljava-4.7.jar:/home/hego555/.m2/repository/org/functionaljava/functionaljava-java8/4.7/functionaljava-java8-4.7.jar:/home/hego555/.m2/repository/org/functionaljava/functionaljava_1.8/4.7/functionaljava_1.8-4.7.jar:/home/hego555/.m2/repository/org/functionaljava/functionaljava-quickcheck/4.7/functionaljava-quickcheck-4.7.jar:/home/hego555/.m2/repository/org/functionaljava/functionaljava-java-core/4.7/functionaljava-java-core-4.7.jar:/home/hego555/.m2/repository/org/mindrot/jbcrypt/0.4/jbcrypt-0.4.jar io.luna.Luna
25 Sep 2018 00:19:58 io.luna.LunaServer [LunaInitializationThread]
INFO: Waiting for 6 launch task(s) to complete...
25 Sep 2018 00:20:24 io.luna.LunaServer [LunaInitializationThread]
INFO: [13/13] Scala plugins have been loaded into memory.
25 Sep 2018 00:20:24 io.luna.LunaServer [LunaInitializationThread]
INFO: The game thread is now running.
25 Sep 2018 00:20:24 io.luna.LunaServer [LunaInitializationThread]
INFO: Luna is now online on port 43594 (took 26s).
25 Sep 2018 00:20:51 io.luna.game.model.mob.Player [LunaGameThread RUNNING]
INFO: Player{username=hego555, index=1, rights=DEVELOPER} has logged in.
25 Sep 2018 00:20:51 io.luna.net.LunaUpstreamHandler [nioEventLoopGroup-2-2]
WARN: Disconnecting GameClient{ip=127.0.0.1}, upstream exception thrown.
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: minimumReadableBytes: -1 (expected: >= 0)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: minimumReadableBytes: -1 (expected: >= 0)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1390) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:843) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.buffer.WrappedByteBuf.readBytes(WrappedByteBuf.java:616) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.buffer.AdvancedLeakAwareByteBuf.readBytes(AdvancedLeakAwareByteBuf.java:473) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.luna.net.codec.game.GameMessageDecoder.payload(GameMessageDecoder.java:164) ~[classes/:?]
	at io.luna.net.codec.game.GameMessageDecoder.decodeMsg(GameMessageDecoder.java:77) ~[classes/:?]
	at io.luna.net.codec.game.GameMessageDecoder.decodeMsg(GameMessageDecoder.java:20) ~[classes/:?]
	at io.luna.net.codec.ProgressiveMessageDecoder.decode(ProgressiveMessageDecoder.java:42) ~[classes/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	... 20 more
25 Sep 2018 00:20:51 io.luna.net.LunaUpstreamHandler [nioEventLoopGroup-2-2]
WARN: Disconnecting GameClient{ip=127.0.0.1}, upstream exception thrown.
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: minimumReadableBytes: -1 (expected: >= 0)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: minimumReadableBytes: -1 (expected: >= 0)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1390) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:843) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.buffer.WrappedByteBuf.readBytes(WrappedByteBuf.java:616) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.buffer.AdvancedLeakAwareByteBuf.readBytes(AdvancedLeakAwareByteBuf.java:473) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.luna.net.codec.game.GameMessageDecoder.payload(GameMessageDecoder.java:164) ~[classes/:?]
	at io.luna.net.codec.game.GameMessageDecoder.decodeMsg(GameMessageDecoder.java:77) ~[classes/:?]
	at io.luna.net.codec.game.GameMessageDecoder.decodeMsg(GameMessageDecoder.java:20) ~[classes/:?]
	at io.luna.net.codec.ProgressiveMessageDecoder.decode(ProgressiveMessageDecoder.java:42) ~[classes/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	... 22 more
25 Sep 2018 00:20:52 io.luna.net.msg.GameMessageReader [LunaGameThread RUNNING]
WARN: Buffer reference count too high [opcode: 0, ref_count: 1]
25 Sep 2018 00:20:52 io.luna.net.msg.GameMessageReader [LunaGameThread RUNNING]
WARN: Buffer reference count too high [opcode: 0, ref_count: 1]
25 Sep 2018 00:20:52 io.luna.net.msg.GameMessageReader [LunaGameThread RUNNING]
WARN: Buffer reference count too high [opcode: 0, ref_count: 1]
25 Sep 2018 00:20:52 io.luna.net.msg.GameMessageReader [LunaGameThread RUNNING]
WARN: Buffer reference count too high [opcode: 0, ref_count: 1]
25 Sep 2018 00:20:52 io.luna.game.model.mob.Player [LunaGameThread RUNNING]
INFO: Player{username=hego555, index=1, rights=DEVELOPER} has logged out.
25 Sep 2018 00:20:54 io.netty.channel.ChannelInitializer [nioEventLoopGroup-2-3]
WARN: Failed to initialize a channel. Closing: [id: 0xb078900e, L:/127.0.0.1:43594 - R:/127.0.0.1:39008]
io.netty.channel.ChannelPipelineException: io.netty.handler.timeout.ReadTimeoutHandler is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:625) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:208) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:201) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.luna.net.LunaChannelInitializer.initChannel(LunaChannelInitializer.java:66) ~[classes/:?]
	at io.luna.net.LunaChannelInitializer.initChannel(LunaChannelInitializer.java:21) ~[classes/:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by lare96** [comment]
The crash actually isn't related to the decoder. It's caused by misuse of shareable channel handlers. These are multiple issues all appearing at once
